In [11]:
import pandas as pd
d=pd.read_excel(r"C:\Users\shiva\Downloads\Book1.xlsx")
df=pd.DataFrame(d)
df

      sepal length  sepal width   petal length  petal width           class
0              5.1          3.5            1.4          0.2     Iris-setosa
1              4.9          3.0            1.4          0.2     Iris-setosa
2              4.7          3.2            1.3          0.2     Iris-setosa
3              4.6          3.1            1.5          0.2     Iris-setosa
4              5.0          3.6            1.4          0.2     Iris-setosa
..             ...          ...            ...          ...             ...
145            6.7          3.0            5.2          2.3  Iris-virginica
146            6.3          2.5            5.0          1.9  Iris-virginica
147            6.5          3.0            5.2          2.0  Iris-virginica
148            6.2          3.4            5.4          2.3  Iris-virginica
149            5.9          3.0            5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [15]:

print(x)

TypeError: cannot do slice indexing on RangeIndex with these indexers [sepal length] of type str

In [16]:
import pandas as pd

data = {
    'Name': ['Ravi', 'Sita', 'Amit', 'John'],
    'Age': [21, 22, 20, 23],
    'Marks': [88, 92, 79, 85]
}

df = pd.DataFrame(data)
print(df)

   Name  Age  Marks
0  Ravi   21     88
1  Sita   22     92
2  Amit   20     79
3  John   23     85

In [46]:
df.iloc[1:4,1:3]

   Age  Marks
1   22     92
2   20     79
3   23     85

### df.iloc[]

In [49]:
df.iloc[3,2]=79

In [50]:
df

   Name  Age  Marks
0  Ravi   21     88
1  Sita   22     92
2  Amit   20     79
3  John   23     79

In [53]:
df["Marks"]=df["Marks"].drop_duplicates()

In [54]:
df["Marks"]=df["marks"].fillna()

   Name  Age  Marks
0  Ravi   21   88.0
1  Sita   22   92.0
2  Amit   20   79.0
3  John   23    NaN