pd.merge(left, right, how='inner', on=None, left_on=None, right_on=None)

In [2]:
import pandas as pd

In [3]:
import pandas as pd

# DataFrame 1
df1 = pd.DataFrame({
    "EmployeeID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"]
})

# DataFrame 2
df2 = pd.DataFrame({
    "EmployeeID": [1, 2, 4],
    "Department": ["HR", "Finance", "IT"]
})

# Merge on EmployeeID
merged = pd.merge(df1, df2, on="EmployeeID", how="inner")
print(merged)

   EmployeeID   Name Department
0           1  Alice         HR
1           2    Bob    Finance

In [4]:
pd.merge(df1,df2,on="EmployeeID",how="outer")

   EmployeeID     Name Department
0           1    Alice         HR
1           2      Bob    Finance
2           3  Charlie        NaN
3           4      NaN         IT

In [49]:
merged=pd.merge(df1,df2,on="EmployeeID",how="left")#it will add all coloms to the left side and match all side of the coloms
print(merged)

   EmployeeID     Name Department
0           1    Alice         HR
1           2      Bob    Finance
2           3  Charlie        NaN

|merged

In [50]:
merged["Department"]=[merged["Department"].max() if pd.isna(dept) else  dept for dept in merged["Department"] ] #absutely it wil show the error because we canto conver the differst data tyepes convert

   EmployeeID     Name Department
0           1    Alice         HR
1           2      Bob    Finance
2           3  Charlie        NaN

In [57]:
merged["Department"]=[merged["Department"].dropna().min() if pd.isna(dept) else  dept for dept in merged["Department"] ]

In [58]:
print(merged)

   EmployeeID     Name Department
0           1    Alice         HR
1           2      Bob    Finance
2           3  Charlie         HR